Generated from configure.in

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1936,7 +1936,7 @@ fi
 
 
 PACKAGE=swftools
-VERSION=2006-10-28-2033
+VERSION=2006-11-05-2341
 
 
 # ------------------------------------------------------------------
@@ -3556,7 +3556,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 { echo "$as_me:$LINENO: checking whether gcc supports lazy variable declaration" >&5
 echo $ECHO_N "checking whether gcc supports lazy variable declaration... $ECHO_C" >&6; }
 
-cat > conftest.cpp << EOF
+cat > conftest.c << EOF
 #include <stdlib.h>
 #include <stdio.h>
 
@@ -3570,7 +3570,7 @@ int main (int argc, char*argv)
 }
 EOF
 
-testprog_link='$CC $CPPFLAGS $CFLAGS conftest.cpp -o conftest${ac_exeext}'
+testprog_link='$CC $CPPFLAGS $CFLAGS conftest.c -o conftest${ac_exeext}'
 if { (eval echo gcc.2.95.m4:19: \"$testprog_link\") 1>&5; (eval $testprog_link) 2>&5; } && test -s conftest${ac_exeext}; then
   { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
@@ -3578,7 +3578,7 @@ echo "${ECHO_T}yes" >&6; }
   export GCC_IS_OK
 else
   echo "configure: failed program was:" >&5
-  cat conftest.cpp >&5
+  cat conftest.c >&5
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
 fi
@@ -19667,7 +19667,7 @@ _ACEOF
 #define WIN32 1
 _ACEOF
 
-	LIBS="$LIBS -lws2_32"
+	LIBS="$LIBS -lws2_32 -lgdi32"
 	{ echo "$as_me:$LINENO: result: mingw" >&5
 echo "${ECHO_T}mingw" >&6; }
     else
@@ -20001,7 +20001,95 @@ else
   JPEGLIBMISSING=true
 fi
 
- #AC_CHECK_LIB(t1, T1_LoadFont,, T1LIBMISSING=true)
+
+{ echo "$as_me:$LINENO: checking for T1_LoadFont in -lt1" >&5
+echo $ECHO_N "checking for T1_LoadFont in -lt1... $ECHO_C" >&6; }
+if test "${ac_cv_lib_t1_T1_LoadFont+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lt1  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char T1_LoadFont ();
+int
+main ()
+{
+return T1_LoadFont ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_t1_T1_LoadFont=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_t1_T1_LoadFont=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_t1_T1_LoadFont" >&5
+echo "${ECHO_T}$ac_cv_lib_t1_T1_LoadFont" >&6; }
+if test $ac_cv_lib_t1_T1_LoadFont = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBT1 1
+_ACEOF
+
+  LIBS="-lt1 $LIBS"
+
+else
+  T1LIBMISSING=true
+fi
+
 
 { echo "$as_me:$LINENO: checking for DGifOpen in -lungif" >&5
 echo $ECHO_N "checking for DGifOpen in -lungif... $ECHO_C" >&6; }
@@ -22208,6 +22296,10 @@ echo "${ECHO_T}yes" >&6; }
 _ACEOF
 
 	cat >>confdefs.h <<_ACEOF
+#define HAVE_FREETYPE_FREETYPE_H 1
+_ACEOF
+
+	cat >>confdefs.h <<_ACEOF
 #define USE_FREETYPE 1
 _ACEOF
   # for ttf2tp1
@@ -23052,14 +23144,14 @@ if test "x${AVIFILE}" '!=' "xtrue" -a "x${AVIFIL32}" '!=' "xtrue"; then
  avi2swf=
 fi
 
-pdf2swf_makefile="pdf2swf/Makefile pdf2swf/xpdf/Makefile"
+pdf2swf_makefile="lib/pdf/Makefile"
 PDF2SWF='pdf2swf$(E)'
 LIBPDF='libpdf$(A)'
 
 if test "x${DISABLEPDF2SWF}" = "xtrue"; then
   echo "* Disabling pdf2swf tool..."
-  rm -f pdf2swf/Makefile
-  echo all install uninstall clean: > pdf2swf/Makefile
+  rm -f lib/pdf/Makefile
+  echo all install uninstall clean: > lib/pdf/Makefile
   pdf2swf_makefile=""
   PDF2SWF=
   LIBPDF=
@@ -23107,7 +23199,7 @@ fi
 # ------------------------------------------------------------------
 
 if test -f "release.in"; then release_in="./release"; fi
-FILES="$release_in Makefile.common ${avi2swf} Makefile lib/Makefile lib/action/Makefile src/Makefile ${pdf2swf_makefile} swfs/Makefile ${pythonrfxswf} ${lame_makefile} lib/art/Makefile"
+FILES="$release_in Makefile.common ${avi2swf} Makefile lib/Makefile lib/action/Makefile src/Makefile ${pdf2swf_makefile} swfs/Makefile pdf2swf/fonts/Makefile ${pythonrfxswf} ${lame_makefile} lib/art/Makefile"
 
 ac_config_files="$ac_config_files ${FILES}"
 
